# Generated by Django 5.2.14 on 2026-06-09 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_referral_referralcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('instructor_signup', 'Referred user became an instructor'), ('paid_course_enrollment', 'Referred user enrolled in paid course')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default='25.00', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earning', to='accounts.referral')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
