# Generated by Django 5.2.14 on 2026-05-15 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='emoji_icon',
        ),
        migrations.AddField(
            model_name='course',
            name='icon_key',
            field=models.CharField(choices=[('hat', 'Graduation cap'), ('chart', 'Chart'), ('at_sign', 'At sign'), ('beaker', 'Beaker'), ('book_open', 'Open book'), ('briefcase', 'Briefcase'), ('calculator', 'Calculator')], default='book_open', help_text='Visual for course cards; SVG lives in static/svg/course-icons/<key>.svg', max_length=32),
        ),
    ]
