# Generated by Django 5.2.14 on 2026-05-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_icon_key_and_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='has_preview',
        ),
        migrations.AlterField(
            model_name='course',
            name='preview_basename',
            field=models.CharField(blank=True, help_text='Optional preview video filename inside videos/courses/<id>/preview/ (e.g. intro.mp4). Leave blank if no preview.', max_length=255),
        ),
    ]
