# Generated by Django 5.2.14 on 2026-05-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_has_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='preview_basename',
            field=models.CharField(blank=True, help_text='Filename only (e.g. intro.mp4). Stored under videos/courses/<id>/preview/. Leave empty if there is no preview.', max_length=255, verbose_name='Preview video (optional)'),
        ),
    ]
