# Generated by Django 5.2.14 on 2026-06-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_enrollment_paid_enrollment_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Internal identifier, e.g. 'instructor_plan'.", max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('stripe_product_id', models.CharField(max_length=255, unique=True)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Populated automatically from Stripe on first checkout. You can also set it manually.', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
