# Generated by Django 5.2.14 on 2026-06-04 02:45

from django.db import migrations


def seed_instructor_plan(apps, schema_editor):
    StripeProduct = apps.get_model("courses", "StripeProduct")
    StripeProduct.objects.get_or_create(
        key="instructor_plan",
        defaults={
            "name": "Instructor Plan",
            "stripe_product_id": "prod_UdihBEByQK5F4A",
            "stripe_price_id": "",
            "active": True,
        },
    )


def unseed_instructor_plan(apps, schema_editor):
    StripeProduct = apps.get_model("courses", "StripeProduct")
    StripeProduct.objects.filter(key="instructor_plan").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0007_stripe_product"),
    ]

    operations = [
        migrations.RunPython(seed_instructor_plan, reverse_code=unseed_instructor_plan),
    ]
