# Generated by Django 5.2.15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def publish_existing_courses(apps, schema_editor):
    Course = apps.get_model("courses", "Course")
    Course.objects.all().update(status="published")


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0008_seed_instructor_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="course",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional sale price. Must be less than the regular price.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                choices=[
                    ("beginner", "Beginner"),
                    ("intermediate", "Intermediate"),
                    ("advanced", "Advanced"),
                ],
                default="beginner",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_review", "Pending review"),
                    ("published", "Published"),
                    ("paused", "Paused"),
                ],
                default="pending_review",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subcategory",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("video_basename", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                    ),
                ),
            ],
            options={"ordering": ["order", "pk"]},
        ),
        migrations.RunPython(publish_existing_courses, migrations.RunPython.noop),
    ]
